name: scrape 
on:
  schedule:
    - cron: '0 12 * * 4'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install pandas hopsworks hsfs[python] == 3.0.0
    - name: Install data scraper
      run: pip install -e git+https://github.com/nicholastwai/UFC_Data_Scraper.git#egg=UFC_Data_Scraper 
    - name: Download python script
      run: wget https://raw.githubusercontent.com/nicholastwai/fight_ds_proj/main/feature_pipeline.py
    - name: Run python script
      env:
          API_KEY: ${{ secrets.API_KEY }}
      run: python feature_pipeline.py
